routes/user.php
<?php

use GuzzleHttp\Client;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware' => 'revalidate'], function () {
  
    Route::get('/', 'HomeController@home')->name('home');
    
    Route::get('/home', 'HomeController@newhome')->name('newhome');
    Route::get('/services', 'HomeController@services')->name('homeservices');
    Route::get('/login', 'HomeController@showLogin')->name('showLogin');
    
    Route::get('/forgot-password', 'HomeController@forgotPassword')->name('forgotPassword');
    Route::post('/reset-password', 'HomeController@resetPassword')->name('resetPassword');
    Route::post('/reset-password/verification', 'HomeController@resetVerification')->name('resetVerification');
    Route::post('/send-email-notification', 'HomeController@send_email_notification')->name('send_email_notification');
    Route::post('/contact-send-email-notification', 'HomeController@send_email_notification_contact')->name('send_email_notification_contact');
   
    // Route::get('/test', 'HomeController@test')->name('test');

    
    Route::group(['namespace'=>'Auth'], function () {
       
        Route::post('/login', 'LoginController@login')->name('login');
        Route::get('/logout', 'LoginController@logout')->name('logout');
        Route::get('/change-password', 'LoginController@changePassword')->name('change_password');
        Route::post('/email-exist', 'LoginController@emailExist')->name('emailExist');
        Route::post('/email-exist-check', 'LoginController@emailExistcheck')->name('emailExistcheck');
        //Route::get('/dashboard/view', 'LoginController@viewdashboard')->name('viewdashboard');
    });
    Route::group(['as'=>'user.'], function () {
        Route::group(['middleware'=>['auth:web']],function(){
            Route::get('/dashboard', 'UserController@viewdashboard')->name('viewdashboard');
        });
    });

    Route::group(['prefix'=>'register','as'=>'user.'], function () {

        Route::get('/', 'UserController@create')->name('register');
        Route::post('/user-type', 'UserController@userType')->name('userType');
        Route::get('/account-details', 'UserController@accountDetails')->name('accountDetails');
      



        
        Route::post('/', 'UserController@store')->name('store');
        Route::get('/{user}/email-verification', 'UserController@emailVerification')->name('emailVerification');
        Route::put('/{user}/email-verification/update', 'UserController@otpVerification')->name('otpVerification');
        Route::post('/resend/email', 'UserController@resendEmail')->name('resendEmail');
       

     

           Route::group(['middleware'=>['auth:web']],function(){
            Route::get('/contact-information', 'UserController@contactInformation')->name('contactInformation');
            Route::post('/contact-information/store', 'UserController@storeContactInformation')->name('storeContactInformation');
            Route::get('/contact-information/view', 'UserController@viewContactInformation')->name('viewContactInformation');

          
            Route::get('/change-password', 'UserController@changePassword')->name('change_password');
            Route::post('/user/change-password', 'UserController@userchangePassword')->name('user.change_password');
            Route::get('/contact-information/edit', 'UserController@editContactInformation')->name('editContactInformation');
            Route::post('/contact-information/update', 'UserController@updateContactInformation')->name('updateContactInformation');
            Route::get('/redirect-back', 'UserController@redirectBack')->name('redirectBack');
            Route::post('/username-exist', 'UserController@usernameExist')->name('usernameExist');
            Route::post('/phonenumber-exist', 'UserController@phoneNumberExist')->name('phoneNumberExist');
            Route::get('/security-questions', 'UserController@securityQuestions')->name('securityQuestions');
            Route::get('/security-questions/edit', 'UserController@editSecurityQuestions')->name('editSecurityQuestions');
            Route::get('/security-questions/view', 'UserController@viewSecurityQuestions')->name('viewSecurityQuestions');
            Route::post('/security-questions/update', 'UserController@updateSecurityQuestions')->name('updateSecurityQuestions');
            Route::post('/security-questions/store', 'UserController@storeSecurityQuestions')->name('storeSecurityQuestions');
            Route::get('/background-check', 'UserController@profileAcknowledgement')->name('profileAcknowledgement');
            Route::post('/payment', 'UserController@oneTimePayment')->name('oneTimePayment');
            Route::post('/store/payment', 'UserController@storeOnePayment')->name('storeOnePayment');
            
            Route::get('/background-verification', 'UserController@backgroundVerification')->name('backgroundVerification');

        });

    });
    Route::group(['prefix'=>'stripe','as'=>'stripe.'], function () {
        Route::post('/save-payment', 'UserController@saveOneTimePayment')->name('saveOneTimePayment');
    });
    Route::group(['prefix'=>'account','as'=>'account.'], function () {
        Route::group(['middleware'=>['auth:web']],function(){
            Route::get('/create-public-profile', 'UserController@createPublicProfile')->name('createPublicProfile');
            Route::post('/create-public-profile/store', 'UserController@storePublicProfile')->name('storePublicProfile');
            Route::get('/view-public-profile', 'UserController@viewPublicProfile')->name('viewPublicProfile');
            Route::get('/{user}/{project}/{status}/details', 'UserController@viewUserDetails')->name('viewUserDetail');
            Route::get('/edit-public-profile', 'UserController@editPublicProfile')->name('editPublicProfile');
            Route::post('/create-public-profile/update', 'UserController@updatePublicProfile')->name('updatePublicProfile');
            Route::get('/{user}/profile', 'UserController@myProfile')->name('myProfile');
        });
    });


    Route::group(['prefix'=>'project','as'=>'project.'], function () {
        Route::group(['middleware'=>['auth:web']],function(){
            Route::get('/create', 'ProjectController@createProject')->name('createProject');
            Route::post('/create/store', 'ProjectController@storeProject')->name('storeProject');
            Route::get('{project}/edit', 'ProjectController@editProject')->name('editProject');
            Route::put('{project}/update', 'ProjectController@updateProject')->name('updateProject');
            Route::get('open-projects', 'ProjectController@listOpenProjects')->name('listOpenProjects');
            Route::get('inporgress-projects', 'ProjectController@listInProgressProjects')->name('listInProgressProjects');

            Route::get('completed-projects', 'ProjectController@listCompletedProjects')->name('listCompletedProjects');

            Route::get('freelancer-inporgress-projects', 'ProjectController@freelancerlistInProgressProjects')->name('freelancerlistInProgressProjects');
            Route::get('{project}/details', 'ProjectController@projectDetails')->name('projectDetails');
            Route::get('{project}/inprogress-project-details', 'ProjectController@inProgressProjectDetails')->name('inProgressProjectDetails');
            Route::get('{project}/completed-project-details', 'ProjectController@completedProjectDetails')->name('completedProjectDetails');
            Route::get('/{project}/details', 'ProjectController@projectDetails')->name('projectDetails');
            Route::get('/{project}/proposals', 'ProjectController@projectProposals')->name('projectProposals');
            Route::get('/{project}/invite-freelancers', 'ProjectController@inviteFreelancers')->name('inviteFreelancers');
            Route::any('/{project}/search-freelancer','ProjectController@searchFreelancers')->name('searchFreelancers'); 
            Route::post('/send-invitation','ProjectController@sendInvitationToFreelancer')->name('sendInvitationToFreelancer');
            Route::get('/invitations','ProjectController@listInvitations')->name('listInvitations');
            Route::get('{project}/invitation-details','ProjectController@viewInvitation')->name('viewInvitation');
            Route::get('{project}/create-proposal','ProjectController@createProposal')->name('createProposal'); 
            Route::post('{project}/store-proposal','ProjectController@storeProposal')->name('storeProposal'); 
            Route::get('/my-proposals','ProjectController@listProposals')->name('listProposals');
            Route::get('{project_proposal}/edit-proposal', 'ProjectController@editProposal')->name('editProposal');
            Route::put('{project_proposal}/update-proposal', 'ProjectController@updateProposal')->name('updateProposal');
            Route::get('{project_contract}/contract', 'ProjectController@prepareContract')->name('prepareContract');
            Route::post('/create-contract', 'ProjectController@createContract')->name('createContract');
            Route::post('/accept-contract', 'ProjectController@acceptProposal')->name('acceptProposal');
            Route::get('/contracts', 'ProjectController@listContracts')->name('listContracts');
            Route::post('/file-upload', 'ProjectController@fileUpload')->name('fileUpload');
            Route::get('/force-download-file', 'ProjectController@forceDownloadFile')->name('forceDownloadFile');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('home');

// Auth::routes();

/**
 * Authentication Management
 */
    Route::group(['prefix'=>'admin','namespace'=>'Auth','as'=>'admin.'], function () {
    Route::get('/','AdminLoginController@showLoginForm')->name('login.form');
    Route::post('login','AdminLoginController@login')->name('login');
    Route::get('logout','AdminLoginController@logout')->name('logout');
    Route::get('login/{social}','AdminLoginController@socialLogin')->where('social','twitter|facebook|linkedin|google|github|bitbucket');
    Route::get('login/{social}/callback','AdminLoginController@handleProviderCallback')->where('social','twitter|facebook|google');
    Route::post('password/email','AdminForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset','AdminForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/reset','AdminResetPasswordController@reset');
    Route::get('password/reset/{token}','AdminResetPasswordController@showResetForm')->name('password.reset');

});

   Route::get('auth/google', 'Auth\AdminLoginController@redirectToGoogle');
   Route::get('auth/google/callback', 'Auth\AdminLoginController@handleGoogleCallback');
   // socialite login ( facebook  and twitter and github)
   Route::get('auth/{provider}', 'Auth\AdminLoginController@redirect');
   Route::get('auth/{provider}/callback', 'Auth\AdminLoginController@callback');


   

/**
 * Admin users portal
 */
    Route::group(['prefix'=>'admin','namespace'=>'Admin','as'=>'admin.','middleware'=>['revalidate','auth:admin']], function () {
    Route::get('dashboard','PageController@dashboard')->name('dashboard');
    /**
     * Admin Roles Management 
     */
        Route::get('roles', 'RoleController@index')->name('roles.index');
        Route::get('role/{role}/show', 'RoleController@show')->name('roles.show');
        Route::get('role/{role}/edit', 'RoleController@edit')->name('roles.edit');
        Route::delete('role/{role}/destroy', 'RoleController@destroy')->middleware('permission:delete roles')->name('roles.destroy');
        Route::put('role/{role}/update','RoleController@update')->middleware('permission:edit roles')->name('roles.update');
        Route::get('role/create','RoleController@create')->middleware('permission:add roles')->name('roles.create');
        Route::post('role/store','RoleController@store')->middleware('permission:add roles')->name('roles.store');
        Route::delete('role/destroy/{role}','RoleController@destroy')->name('roles.destroy');
    /**
     *Admins Management  
     */    
        Route::get('admin-users/{role?}/{status?}','AdminController@index')->middleware('permission:list admin users')->name('admins.index');
        Route::get('admin-user/{admin}/edit/{role?}','AdminController@edit')->middleware('permission:edit admin users')->name('admins.edit');
        Route::get('admin/{admin}/edit/{role?}','AdminController@editprofile')->name('admins.profile-edit');
        Route::put('admin-user/{admin}/updates/{role?}','AdminController@update')->middleware('permission:edit admin users')->name('admins.update');
        Route::put('admin-user/{admin}/update/{role?}','AdminController@updateprofile')->name('admins.updateprofile');
        Route::delete('admin-user/{admin}/destroy','AdminController@destroy')->name('admins.destroy');
        Route::get('admin-user/create/{role?}','AdminController@create')->middleware('permission:add admin users')->name('admins.create');
        Route::post('admin-user/store/{role?}','AdminController@store')->middleware('permission:add admin users')->name('admins.store');
        Route::get('admin-user/{admin}/show/{role?}','AdminController@show')->middleware('permission:view admin users')->name('admins.show');
        Route::get('admin-user/{admin}/access-logs','AdminController@accessLogs')/* ->middleware('permission:list admin user access logs') */->name('admins.access_logs');
        Route::get('admin-user/{admin}/activity-logs/{role?}','AdminController@activityLogs')/* ->middleware('permission:list admin user activity logs') */->name('admins.activity_logs');
        
    /**
     * Industries
     */
        Route::get('industries', 'IndustryController@index')->middleware('permission:list industries')->name('industries.index');
        Route::post('industries/store','IndustryController@store')->middleware('permission:add industries')->name('industries.store');
        Route::put('industries/{industry}/update','IndustryController@update')->middleware('permission:edit industries')->name('industries.update');
        Route::delete('industries/{industry}/destroy','IndustryController@destroy')->middleware('permission:delete industries')->name('industries.destroy');
        Route::put('industries/toggle-active-status/{id}', 'IndustryController@toggleActiveStatus')->name('industries.changeStatus');

    /**
     * Categories
     */
       Route::get('categories', 'CategoryController@index')->middleware('permission:list categories')->name('categories.index');
       Route::get('categories/create','CategoryController@create')->middleware('permission:add categories')->name('categories.create');
       Route::post('categories/store','CategoryController@store')->middleware('permission:add categories')->name('categories.store');
       Route::get('categories/{category}/edit', 'CategoryController@edit')->middleware('permission:edit categories')->name('categories.edit');
       Route::get('categories/{category}/show', 'CategoryController@show')->middleware('permission:show categories')->name('categories.show');
       Route::put('categories/{category}/update','CategoryController@update')->middleware('permission:edit categories')->name('categories.update');
       Route::delete('categories/{category}/destroy','CategoryController@destroy')->middleware('permission:delete categories')->name('categories.destroy');
       Route::put('categories/toggle-active-status/{id}', 'CategoryController@toggleActiveStatus')->name('categories.changeStatus');

       /**
        *Sub Categories 
       */

       Route::get('sub-categories', 'SubCategoryController@index')->middleware('permission:list subcategories')->name('sub_categories.index');
       Route::get('sub-categories/create','SubCategoryController@create')->middleware('permission:add subcategories')->name('sub_categories.create');
       Route::post('sub-categories/store','SubCategoryController@store')->middleware('permission:add subcategories')->name('sub_categories.store');
       Route::get('sub-categories/{subCategory}/show', 'SubCategoryController@show')->middleware('permission:show subcategories')->name('sub_categories.show');
       Route::get('sub-categories/{subCategory}/edit', 'SubCategoryController@edit')->middleware('permission:edit subcategories')->name('sub_categories.edit');
       Route::put('sub-categories/{subCategory}/update','SubCategoryController@update')->middleware('permission:edit subcategories')->name('sub_categories.update');
       Route::delete('sub-categories/{subCategory}/destroy','SubCategoryController@destroy')->middleware('permission:delete subcategories')->name('sub_categories.destroy');
       Route::put('sub-categories/toggle-active-status/{id}', 'SubCategoryController@toggleActiveStatus')->name('sub_categories.changeStatus');

       /**
        * Skills
        */
       Route::get('skills', 'SkillController@index')->middleware('permission:list skills')->name('skills.index');
       Route::get('skills/create','SkillController@create')->middleware('permission:add skills')->name('skills.create');
       Route::post('skills/store','SkillController@store')->middleware('permission:add skills')->name('skills.store');
       Route::get('skills/{skill}/show', 'SkillController@show')->middleware('permission:show skills')->name('skills.show');
       Route::get('skills/{skill}/edit', 'SkillController@edit')->middleware('permission:edit skills')->name('skills.edit');
       Route::put('skills/{skill}/update','SkillController@update')->middleware('permission:edit skills')->name('skills.update');
       Route::delete('skills/{skill}/destroy','SkillController@destroy')->middleware('permission:delete skills')->name('skills.destroy');
       Route::put('skills/toggle-active-status/{id}', 'SkillController@toggleActiveStatus')->name('skills.changeStatus');
      
       /**
        * Membership plans
        */
        Route::get('membership-plans', 'MembershipPlanController@index')->middleware('permission:list membership plan')->name('membership_plans.index');
        Route::get('membership-plans/create','MembershipPlanController@create')->middleware('permission:add membership plan')->name('membership_plans.create');
        Route::post('membership-plans/store','MembershipPlanController@store')->middleware('permission:add membership plan')->name('membership_plans.store');
        Route::get('membership-plans/{membershipPlan}/edit', 'MembershipPlanController@edit')->middleware('permission:edit membership plan')->name('membership_plans.edit');
        Route::put('membership-plans/{membershipPlan}/update','MembershipPlanController@update')->middleware('permission:edit membership plan')->name('membership_plans.update');
        Route::get('membership-plans/{membershipPlan}/show', 'MembershipPlanController@show')->middleware('permission:view membership plan')->name('membership_plans.show');

resources/views/admin/admins/access_logs.blade.php
@extends('admin.layouts.app')
@section('title', set_page_titile(__('Access Logs')))
@push('custom-styles')
{{ style(mix('vendor/datatable/css/datatable.css')) }}
@endpush
@section('content')
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                {{ Breadcrumbs::render('admin_users.access_logs',$admin) }}
            </div>
            <h4 class="page-title">{{ ucwords($admin->roles()->first()->name)."'s Details"}}</h4>
        </div>
    </div>
</div>
@include('admin.includes.profile.profile_head')
<div class="row">
    @include('admin.includes.profile.tab_head')
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                <div class="tab-content" id="v-pills-tabContent">
                    @include('admin.includes.profile.tabs.access_logs')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('custom-scripts')
{!! script(mix('vendor/datatable/js/datatable.js')) !!}
{!! $html->scripts() !!}
@endpush

resources/views/admin/admins/activity_logs.blade.php
@extends('admin.layouts.app')
@section('title', set_page_titile(__('Activity Logs')))
@push('custom-styles')
{{ style(mix('vendor/datatable/css/datatable.css')) }}
@endpush
@section('content')
<div class="row">
    <div class="col-12">
        <div class="page-title-box">
            <div class="page-title-right">
                {{ Breadcrumbs::render('admin_users.activity_logs',$admin) }}
            </div>
            <h4 class="page-title">{{ ucwords($admin->roles()->first()->name)."'s Details"}}</h4>
        </div>
    </div>
</div>
@include('admin.includes.profile.profile_head')
<div class="row">
    @include('admin.includes.profile.tab_head')
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                <div class="tab-content" id="v-pills-tabContent">
                    @include('admin.includes.profile.tabs.activity_logs')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('custom-scripts')
@endpush

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.app')
@section('title', set_page_titile(__('Admin Users Listing')))
@push('custom-styles')
{{ style(mix('vendor/datatable/css/datatable.css')) }}
@endpush
@section('content')

<div class="row">
    <div class="col-12">
        
        <div class="page-title-box">        
            {{ Breadcrumbs::render('admin_users') }}
            <h4 class="page-title">{{ __('Admin Users') }}</h4>
            
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <ul class="nav nav-pills bg-nav-pills nav-justified mb-3">
                    <li class="nav-item">
                        <a href="{{ route('admin.admins.index') }}" aria-expanded="false" class="nav-link rounded-0 @if(empty($role)) active @endif">
                            <i class="mdi mdi-home-variant d-lg-none d-block mr-1"></i>
                            <span class="d-none d-lg-block">{{ __('All') }}</span>
                        </a>
                    </li>
                    @foreach($roles as $get_role)
                        <li class="nav-item border-right border-left">
                            <a href="{{ route('admin.admins.index',str_replace(" ","-",$get_role->name)) }}" aria-expanded="true" class=" nav-link rounded-0 @if(str_replace("-"," ",$role) == $get_role->name) active @endif">
                                <i class="mdi mdi-account-circle d-lg-none d-block mr-1"></i>
                                <span class="d-none d-lg-block">{{ ucwords($get_role->name) }}</span>
                            </a>
                        </li>
                    @endforeach
                </ul>
                <div class="row">
                    <div class="col-sm-4">
                        @can('add admin users')
                            <button onclick="location.href='{{ route('admin.admins.create',$role) }}'" type="button" class="btn btn-danger mb-3"><i class="mdi mdi-plus"></i> {{ __('Admin User') }}</button>
                        @endcan
                    </div>
                    <div class="col-sm-8">
                        <div class="text-sm-right">
                            <div class="btn-group mb-3 ml-1 status-btns">
                                <button type="button" data-type="all" class="btn btn-primary">{{ __('All') }}</button>
                                <button type="button" data-type="active" class="btn btn-light">{{ __('Active') }}</button>
                                <button type="button" data-type="inactive" class="btn btn-light">{{ __('In Active') }}</button>
                            </div>
                            <input type="hidden" name="status_filter" id="status-filter" value="">
                        </div>
                    </div>
                </div>
                <div id="basic-datatable_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                    <div class="row">
                        <div class="col-sm-12">
                            {!! $dataTable->table(['class' => 'table nowrap table-striped','id'=>'basic-datatable'], true) !!}
                            <div class="col-12 text-right px-0">
                                <div class="form-group row">
                                    <label class="col-sm-11 col-form-label">{{ __('Jump to page :') }}</label>
                                    <div class="col-sm-1 mt-1">
                                        <input type="text" id="pageNum" class="form-control form-control-sm">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div> <!-- end card body-->
        </div> <!-- end card -->
    </div><!-- end col-->
</div>
@endsection
@push('custom-scripts')
{!! script(mix('vendor/datatable/js/datatable.js')) !!}
{!! $dataTable->scripts() !!}
<script>
    $('.nav-item a').each(function(){
        if($(this).hasClass('active')){
            $(this).parent().css('background-color','#dedfe6');
        }
    });

   $(document).on('click','.btn-group button',function(){
       $('#status-filter').val($(this).attr('data-type'));
       $('#basic-datatable').DataTable().draw();
   })
   $(document).on('change','input[type=checkbox]',function(){
        Swal.fire({
            title: 'Are you sure?',
            text: "The current status of the admin user will be changed.",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, Update Status!'
        }).then((result) => {
            if (result.value) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $.ajax({
                    type: "GET",
                    url: "/admin/toggle-active-status/"+$(this).attr('data-admin')
                });
                Swal.fire(
                    'Status Updated!',
                    'The status of the admin user has been updated.',
                    'success'
                )
                setTimeout(function(){
                $(".status-btns .btn-primary").click();
                },1);
            } else {
                if($(this).prop("checked") ==  true){
                    $(this).prop("checked",false);
                } else {
                    $(this).prop("checked",true);
                }
            }
        })
   })
</script>
<script>
    $("document").ready(function () {
        $('.status-btns button:first-of-type').addClass('btn-primary');
    });
    $('.status-btns button').click(function(){
        $(this).addClass('btn-primary');
        $(this).siblings().removeClass('btn-primary');
        $(this).siblings().addClass('btn-light');
        $(this).removeClass('btn-light');
    });
</script>
@endpush

resources/views/admin/admins/show.blade.php
@extends('admin.layouts.app')
@section('title', set_page_titile(__($admin->name.' - Admin Users')))
@push('custom-styles')
@endpush
@section('content')
<div class="row">
    <div class="col-12">
        <div class="page-title-box">            
            {{ Breadcrumbs::render('admin_users.show',$admin) }} 
            @if(auth()->user()->id != $admin->id)           
            <h4 class="page-title">{{$admin->name}}{{ __("'s Profile")}}</h4>
            @else 
                <h4 class="page-title">{{ "My Account"}}</h4>
            @endif
        </div>
    </div>
</div>
@include('admin.includes.profile.profile_head')
<div class="row">
    @include('admin.includes.profile.tab_head')
    <div class="col-md-9">
        <!-- Personal-Information -->
        <div class="card">
            <div class="card-body">
                <div class="tab-content" id="v-pills-tabContent">
                    @include('admin.includes.profile.tabs.profile')
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('custom-scripts')
@endpush